# Generated by Django 4.1.4 on 2023-06-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_number", models.CharField(max_length=10)),
                ("department_name", models.CharField(max_length=100)),
                ("hod_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_order_number", models.CharField(max_length=10)),
                ("purchase_date", models.DateField()),
                ("supplies", models.TextField()),
                (
                    "purchase_order_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                ("lab_id", models.AutoField(primary_key=True, serialize=False)),
                ("lab_number", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=100)),
                ("lab_incharge", models.CharField(max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cse_lab.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_serial_number", models.CharField(max_length=50)),
                ("purchase_date", models.DateField()),
                (
                    "equipment_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField()),
                ("invoice", models.ImageField(upload_to="invoices/")),
                ("status", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cse_lab.lab"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cse_lab.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
