# Generated by Django 4.1.4 on 2023-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cse_lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment", models.CharField(max_length=100)),
                ("lab", models.CharField(max_length=100)),
                ("number_of_equipments", models.IntegerField()),
                ("details", models.TextField()),
            ],
        ),
    ]
