# Generated by Django 4.1.4 on 2023-06-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cse_lab", "0002_equipmentissue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="supplies",
            new_name="supplier",
        ),
    ]
