# Generated by Django 4.1.4 on 2023-07-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cse_lab", "0003_rename_supplies_purchaseorder_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("date", models.DateField()),
                ("lab_incharge_name", models.CharField(max_length=100)),
                ("not_working_quantity", models.IntegerField()),
                ("remarks", models.TextField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cse_lab.equipment",
                    ),
                ),
            ],
        ),
    ]
