# Generated by Django 4.2.5 on 2023-09-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.CharField(max_length=10)),
                ('department_name', models.CharField(max_length=100)),
                ('hod_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_serial_number', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('equipment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('invoice', models.ImageField(upload_to='invoices/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.CharField(max_length=10, unique=True)),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('lab_incharge_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.department')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('lab_incharge_name', models.CharField(max_length=100)),
                ('not_working_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=100)),
                ('number_of_equipments', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.purchaseorder'),
        ),
    ]
