# Generated by Django 4.2.5 on 2023-09-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='equipmentissue',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='equipmentreview',
            name='lab_incharge_name',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='lab_incharge_name',
        ),
        migrations.CreateModel(
            name='LabInCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_incharge_name', models.CharField(max_length=100)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='lab_incharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab.labincharge'),
        ),
        migrations.AddField(
            model_name='equipmentreview',
            name='lab_incharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab.labincharge'),
            preserve_default=False,
        ),
    ]
