# Generated by Django 4.1.4 on 2023-09-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_alter_labinchargelogin_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LabInchargeLogin",
        ),
    ]
