# Generated by Django 4.1.4 on 2023-09-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0008_delete_labinchargelogin"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabInchargeLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_incharge_login_emails",
                        to="lab.labinchargeregister",
                    ),
                ),
                (
                    "password",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_incharge_login_passwords",
                        to="lab.labinchargeregister",
                    ),
                ),
            ],
        ),
    ]
