# Generated by Django 4.2.5 on 2023-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_remove_labinchargeregister_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
